// Embeds POSTING_KNOWLEDGE.md into netlify/lib/knowledge.mjs (served by /api/v1/knowledge and the get_knowledge MCP tool).
import { readFileSync, writeFileSync } from "node:fs";
const md = readFileSync(new URL("./POSTING_KNOWLEDGE.md", import.meta.url), "utf8");
writeFileSync(new URL("../netlify/lib/knowledge.mjs", import.meta.url), `// generated by knowledge/build.mjs, do not edit\nexport const KNOWLEDGE_MD = ${JSON.stringify(md)};\n`);
console.log("knowledge.mjs", md.length, "chars");
